make:
	gcc assignment2.c -o assignment2
	gcc rm.c -o rm
	gcc cat.c -o cat
	gcc date.c -o date
	gcc ls.c -o ls
	gcc mkdir.c -o mkdir
	gcc mkdir2.c -o mkdir2
	gcc ls1.c -o ls1
	gcc ls2.c -o ls2
	gcc date2.c -o date2
